Update Python versions
ppb/ppb-vector pull request #199
Opened 2021-04-14 23:08 UTC by AstraLuma

Semi-annual touching of python versions.

2021-04-15 00:04 UTC, AstraLuma commented
(Thanks to @duckinator for helping on the FreeBSD issue)

2021-10-14 03:39 UTC, AstraLuma commented
@pathunstrom how's this look?

2021-10-23 12:58 UTC, nicoonoclaste requested changes
LGTM overall, but there are a few things I'd like answered or changed.

2021-10-23 12:58 UTC, nicoonoclaste commented on ppb_vector/__init__.py
> +            raise TypeError(f"{type(x).__name__} object not convertable to float") from None
Are we sure the lint is invalid and `from None` is the right thing here? (and same right below)

2021-10-23 12:58 UTC, nicoonoclaste commented on .cirrus.yml
> +  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
We probably don't want to run that on all branches etc.

```suggestion
  skip: $CIRRUS_BRANCH =~ 'canon'
```

2021-10-23 12:58 UTC, nicoonoclaste commented on .cirrus.yml
> +      - IMAGE: python:3.10-slim
Since we are using `rc-slim` below to always get the latest dev. version, why not use `3-slim` here and only use major version numbers for the older entries?

I think this would be more coherent, and has the advantage of always tracking the latest stable Python version even if we forgot to update the CI config.

```suggestion
      - IMAGE: python:3-slim
```

2021-10-23 12:58 UTC, nicoonoclaste commented on .cirrus.yml
> +      - IMAGE: python:3.10-windowsservercore
Same, `3-windowsservercore`

2021-10-23 14:17 UTC, AstraLuma commented on ppb_vector/__init__.py
> +            raise TypeError(f"{type(x).__name__} object not convertable to float") from None
I honestly haven't looked into why these lint rules exist.

2021-10-23 14:18 UTC, AstraLuma commented on .cirrus.yml
> +      - IMAGE: python:3.10-slim
I like specifically listing the major versions. We should also list the development head, though.

2021-10-23 16:52 UTC, nicoonoclaste commented
@AstraLuma Should I deal with the merge conflict for you?

2021-10-23 16:53 UTC, nicoonoclaste commented on .cirrus.yml
> +      - IMAGE: python:3.10-slim
I guess the Linux and Windows CI are fast enough the duplicated work shouldn't be an issue.

2021-10-23 16:57 UTC, AstraLuma commented on .cirrus.yml
> +      - IMAGE: python:3.10-slim
well, over the course of the year, the dev version will diverge from the last release. Testing against it gives us a heads up if a future change is going to break something.

Extremely unlikely for `ppb-vector`, but we might as well.

2021-10-23 17:08 UTC, AstraLuma commented
Handled.

2021-10-24 21:42 UTC, AstraLuma commented on ppb_vector/__init__.py
> +            raise TypeError(f"{type(x).__name__} object not convertable to float") from None
Ok, in Python there's two forms of chaining, explicit and implicit, which use different special attributes to distinguish them and different messages ("the above was the direct cause of ..." vs "while handling the above exception, another exception occurred").

This lint rule is to force wrapper exceptions to use the former path and message rather than the latter, which is strictly speaking a better error message.

2021-10-25 06:46 UTC, nicoonoclaste commented on .cirrus.yml
> +      - IMAGE: python:3.10-slim
Oh, I think we misunderstood one-another. I wasn't suggesting not to test against `rc-slim` or such, I was suggesting that we should refer to the latest release as just `3-silm` (which always points to the latest stable release, AFAIK) so if we forget to update the version number we are still testing against the latest stable anyhow.

2021-10-25 06:47 UTC, nicoonoclaste approved these changes
LGTM, remaining nit can be picked in a later PR.

2021-10-25 06:47 UTC, nicoonoclaste commented
bors r+

2021-10-25 07:20 UTC, merged