Improve annotations and comments
ppb/ppb-vector pull request #209
Opened 2021-10-26 18:48 UTC by nicoonoclaste

- `VectorLike`
  * Nix obsoleted comment
  * Refine type definition for mappings
- Comment `Vector.__match_args__`
- Simplify references to the `typing` module
- Document deprecation of typing.{Sequence, Tuple, ...} from Python 3.9 onwards
- `lint.sh`: Avoid linting `.eggs/` and other directories

2021-10-26 21:29 UTC, AstraLuma requested changes

2021-10-26 21:29 UTC, AstraLuma commented on ppb_vector/__init__.py
> +          :py:class:`SupportsFloat`), return
According to [the docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects) sphinx does not follow python's rules for name resolution.

2021-10-26 21:29 UTC, AstraLuma commented on ppb_vector/__init__.py
> +          :py:class:`SupportsFloat`), return
(but it might work anyway with the exhaustive search.)

2021-10-26 21:29 UTC, AstraLuma commented on setup.py
> +    setup_requires=requirements() + ['pytest-runner'],
pretty sure that's an `install_requires`.... not sure why it lists `pytest-runner` here, too.

2021-10-26 21:36 UTC, pathunstrom commented on ppb_vector/__init__.py
> +          :py:class:`SupportsFloat`), return
You can remove the `typing` by prepending a tilde: :class:`~events.Idle`

2021-10-26 22:02 UTC, nicoonoclaste commented on ppb_vector/__init__.py
> +          :py:class:`SupportsFloat`), return
Wow, rude.  OK I'll change that

2021-10-26 22:04 UTC, nicoonoclaste commented on setup.py
> +    setup_requires=requirements() + ['pytest-runner'],
Mew?  THe comment above should clarify: `setup` needs to be able to import the library, which itself imports from `typing_extensions` on Py3.7.

Yopu are right though ths shloud abe a `install_require` too

2021-10-26 22:10 UTC, AstraLuma commented on setup.py
> +    setup_requires=requirements() + ['pytest-runner'],
Oh, I'll have to look at this more closely then.

2021-10-27 05:44 UTC, nicoonoclaste commented
@AstraLuma Handled the requested changes and fixed the merge conflict.

2021-10-27 13:26 UTC, AstraLuma approved these changes

2021-10-27 19:00 UTC, nicoonoclaste commented
Feel free to merge my PRs when you approve them; if they aren't ready I'm make them be drafts.
bors r=astraluma

2021-10-27 19:25 UTC, merged